import type { CanvasElement } from '../hooks/useCanvasElements';

export interface DocumentTemplate {
  id: string;
  name: string;
  icon: string;
  description: string;
  category: string;
  elements: Omit<CanvasElement, 'id' | 'zIndex'>[];
}

/** Modèles de proposition par défaut — uniquement des variables existantes (patient, docteur, cabinet, acte, posologie, user, collaborateur). */
export const DOCUMENT_TEMPLATES: DocumentTemplate[] = [
  {
    id: 'prop_ordre_classique',
    name: 'Ordonnance (proposition)',
    icon: '📋',
    description: 'En-tête cabinet, patient et zone prescription ({{posologie.texte}})',
    category: 'prescription',
    elements: [
      {
        type: 'text',
        x: 50,
        y: 40,
        width: 694,
        height: 36,
        content: 'ORDONNANCE',
        fontSize: 22,
        fontFamily: 'Georgia, serif',
        color: '#2c3e50',
        fontWeight: 'bold',
        textAlign: 'center',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 85,
        width: 400,
        height: 22,
        content: '{{cabinet.nom}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#34495e',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 108,
        width: 500,
        height: 20,
        content: '{{cabinet.adresse}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#546e7a',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 150,
        width: 120,
        height: 20,
        content: 'Patient :',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        fontWeight: 'bold',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 130,
        y: 150,
        width: 200,
        height: 20,
        content: '{{patient.nom}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 340,
        y: 150,
        width: 200,
        height: 20,
        content: '{{patient.prenom}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 178,
        width: 180,
        height: 20,
        content: 'Né(e) le :',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'bold',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 140,
        y: 178,
        width: 200,
        height: 20,
        content: '{{patient.naissance}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 230,
        width: 200,
        height: 22,
        content: 'Prescription',
        fontSize: 13,
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'bold',
        color: '#2980b9',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 258,
        width: 694,
        height: 280,
        content: '{{posologie.texte}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: '#f8f9fa',
        borderColor: '#bdc3c7',
        borderWidth: 1,
      },
      {
        type: 'text',
        x: 50,
        y: 560,
        width: 200,
        height: 18,
        content: 'Date :',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'bold',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 100,
        y: 560,
        width: 200,
        height: 18,
        content: '{{posologie.date}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 400,
        y: 1000,
        width: 340,
        height: 60,
        content: 'Signature',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#7f8c8d',
        textAlign: 'center',
        fontStyle: 'italic',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 400,
        y: 1025,
        width: 340,
        height: 22,
        content: '{{docteur.prenom}} {{docteur.nom}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        textAlign: 'center',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
    ],
  },
  {
    id: 'prop_posologie_detail',
    name: 'Posologie (proposition)',
    icon: '💊',
    description: 'Rappel structuré {{posologie.lignes}} avec cabinet et praticien',
    category: 'prescription',
    elements: [
      {
        type: 'text',
        x: 50,
        y: 40,
        width: 694,
        height: 32,
        content: 'POSOLOGIE',
        fontSize: 20,
        fontFamily: 'Georgia, serif',
        color: '#2c3e50',
        fontWeight: 'bold',
        textAlign: 'center',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 82,
        width: 350,
        height: 20,
        content: '{{cabinet.nom}} — {{cabinet.pays}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#546e7a',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 120,
        width: 80,
        height: 20,
        content: 'Patient',
        fontSize: 12,
        fontWeight: 'bold',
        fontFamily: 'Arial, sans-serif',
        color: '#2980b9',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 145,
        width: 400,
        height: 22,
        content: '{{patient.nom}} {{patient.prenom}} — {{patient.telephone}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 190,
        width: 694,
        height: 360,
        content: '{{posologie.lignes}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: '#fffef7',
        borderColor: '#f1c40f',
        borderWidth: 1,
      },
      {
        type: 'text',
        x: 50,
        y: 570,
        width: 120,
        height: 18,
        content: 'Praticien :',
        fontSize: 11,
        fontWeight: 'bold',
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 130,
        y: 570,
        width: 400,
        height: 18,
        content: '{{docteur.prenom}} {{docteur.nom}} — {{docteur.telephone}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
    ],
  },
  {
    id: 'prop_releve_compte',
    name: 'Relevé de compte (proposition)',
    icon: '💶',
    description: 'Patient, acte courant et montants ({{acte.*}})',
    category: 'administratif',
    elements: [
      {
        type: 'text',
        x: 50,
        y: 40,
        width: 694,
        height: 32,
        content: 'RELEVÉ DE COMPTE',
        fontSize: 20,
        fontFamily: 'Georgia, serif',
        color: '#2c3e50',
        fontWeight: 'bold',
        textAlign: 'center',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 85,
        width: 500,
        height: 22,
        content: '{{cabinet.nom}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#34495e',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 130,
        width: 100,
        height: 20,
        content: 'Patient',
        fontSize: 12,
        fontWeight: 'bold',
        fontFamily: 'Arial, sans-serif',
        color: '#2980b9',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 155,
        width: 500,
        height: 22,
        content: '{{patient.nom}} {{patient.prenom}} — {{patient.login}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 200,
        width: 120,
        height: 20,
        content: 'Acte',
        fontSize: 12,
        fontWeight: 'bold',
        fontFamily: 'Arial, sans-serif',
        color: '#2980b9',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 225,
        width: 500,
        height: 22,
        content: '{{acte.nom}}',
        fontSize: 12,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 258,
        width: 80,
        height: 18,
        content: 'Date :',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        fontWeight: 'bold',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 110,
        y: 258,
        width: 200,
        height: 18,
        content: '{{acte.date}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 290,
        width: 120,
        height: 18,
        content: 'Prix :',
        fontSize: 11,
        fontWeight: 'bold',
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 110,
        y: 290,
        width: 120,
        height: 18,
        content: '{{acte.prix}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 280,
        y: 290,
        width: 140,
        height: 18,
        content: 'Montant total :',
        fontSize: 11,
        fontWeight: 'bold',
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 390,
        y: 290,
        width: 120,
        height: 18,
        content: '{{acte.montantTotal}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 318,
        width: 140,
        height: 18,
        content: 'Reçu :',
        fontSize: 11,
        fontWeight: 'bold',
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 110,
        y: 318,
        width: 100,
        height: 18,
        content: '{{acte.argentRecu}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 280,
        y: 318,
        width: 160,
        height: 18,
        content: 'Restant dû :',
        fontSize: 11,
        fontWeight: 'bold',
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 370,
        y: 318,
        width: 120,
        height: 18,
        content: '{{acte.argentRestant}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#c0392b',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'text',
        x: 50,
        y: 380,
        width: 200,
        height: 18,
        content: 'Établi par (compte connecté) :',
        fontSize: 10,
        fontFamily: 'Arial, sans-serif',
        color: '#7f8c8d',
        backgroundColor: 'transparent',
        borderWidth: 0,
      },
      {
        type: 'variable',
        x: 50,
        y: 400,
        width: 400,
        height: 20,
        content: '{{user.prenom}} {{user.nom}}',
        fontSize: 11,
        fontFamily: 'Arial, sans-serif',
        color: '#2c3e50',
        backgroundColor: 'transparent',
        borderColor: 'transparent',
        borderWidth: 0,
      },
    ],
  },
];
